name: glowberry-github-actions-docker-compose-terraform-koyeb

on:
  push:
    branches:
      - main


env:
  TF_LOG: INFO
  TF_INPUT: false


jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.11.4"
    
          
      - name: Terraform Deploy
        id: init
        run: |
          - export KOYEB_TOKEN=${{secrets.KOYEB_API_TOKEN}}
          - terraform init -backend=false
          - terraform fmt -check
          - terraform validate -no-color || true 
          - terraform plan -no-color
          - terraform apply -auto-approve